### ISSUE TITLE
usage documentation 

### ISSUE THREAD

**Issue by aless3** [sakul987/wiretainer#3]
Can you please expand on what the multi mode does (like why is is needed and/or not the default), and how to run applications with some examples? 
Also the All In One Line section is not very clear to me (but probably because I did not understand well the rest). 

English is not my native language, this may be the reason, sorry for that! 

Thank you so much!
Seems a very interesting utility!

**Comment by sakul987** [comment]
When not using multi mode, you can only have 1 connection open which will have the netns name "vpn". This will be the "default" connection, so you don't have to specify the server when running a command like "wg-container exec curl ip.me". To start in normal mode, just call "wg-container up wgConfigName" and to stop it run "wg-container down".

Multi mode ist just saying I want to have more than the default vpn but then you have to specify which you mean. To start run "wg-container up -m wgConfigName", to execute something inside run "wg-container exec -m wgConfigName curl ip.me" and to stop run "wg-container down -m wgConfigName".

wgConfigName can be something like "wg-us-01". In case it's unclear, using or not using multi mode is no "global setting", it just applies to the current command you are executing. You can run all connections in multi mode without a default connection.

The all in one / direct mode is used when you only want to run something like firefox in a vpn and don't care about using the connection for other applications. With this, you just have to specify which server you want to route the application traffic through like "wg-container direct wg-us-01 curl ip.me". The script will automatically start the connection, execute your command and stop the connection when the command has finished. For example you can run firefox with direct mode and when you are done and close firefox, the connection will be closed. You don't have to manually start and stop the connection.

I hope this helps

**Comment by aless3** [comment]
thank you very much!
